### ISSUE TITLE
error when changing to Brazilian Portuguese language

### ISSUE THREAD

**Issue by GMDiegoLima** [LOUDO56/PyMacroRecord#43]
**To Reproduce**
Start the project from the cloned repository and change the language to brazilian portuguese try to restart and get the error

**Error**
```
Traceback (most recent call last):
  File ".../src/main.py", line 10, in <module>
    MainApp()
  File ".../src/windows/main/main_app.py", line 54, in __init__
    self.menu = MenuBar(self)  # Menu Bar
                ^^^^^^^^^^^^^
  File ".../src/windows/main/menu_bar.py", line 49, in __init__
    playback_sub.add_command(label=self.text_config["options_menu"]["playback_menu"]["fixed_hour_text"], command=lambda: TimeGui(self, parent, "Fixed_hour"))
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'fixed_hour_text'
```

**The OS**
Linux Mint 22 Cinnamon

**Comment by LOUDO56** [comment]
Oops, yeah sorry I'm currently working on a new feature, I should've been working on a separated branch, my bad.
Reset hard on this commit, `git reset --hard 1d11d49` for now, I'll create a separated branch later
