### ISSUE TITLE
Closed it with task manager, wont start after that.

### ISSUE THREAD

**Issue by bruuhen** [LOUDO56/PyMacroRecord#7]
Traceback (most recent call last):
  File "global_function.py", line 53, in loadRecord
    return load(open(path.join(userSettingsPath)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 42 column 1 (char 818)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "software.py", line 130, in <module>
  File "global_function.py", line 56, in loadRecord
    return load(open(path.join(userSettingsPath)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 42 column 1 (char 818)

**Comment by LOUDO56** [comment]
Hello, what OS do you use?

**Comment by LOUDO56** [comment]
This bug is weird, I took some time to find the issue but I found it, i'll fix it in the next update.
So to fix it for now go to Appdata folder `windows + r`, then go to Local/PyMacroRecord. Open `userSettings.json` and remove the extra `}` at the end of the file.
This should fix the problem.
